import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
import { WalletConnectProvider } from "@/providers/wallet-connect-provider";
import RecoilContextProvider from "@/providers/recoil-provider";

// const goodTiming = localFont({
//   src: " ./fonts/good-timing/good-timing-bd.otf",
//   variable: "--font-good-timing",
// });

export const metadata: Metadata = {
  title: "Conntree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <body className={`${goodTiming.variable} antialiased`}></body> */}
        <RecoilContextProvider>
          <WalletConnectProvider>{children}</WalletConnectProvider>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
