import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import RecoilContextProvider from "@/providers/recoil-provider";
import { WalletConnectProvider } from "@/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const goodTiming = localFont({
  src: "./fonts/good-timing-bd.otf",
  variable: "--font-good-timing",
});

export const metadata: Metadata = {
  title: "Conntree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${goodTiming.variable} antialiased`}
      >
        <RecoilContextProvider>
          <WalletConnectProvider>{children}</WalletConnectProvider>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
