import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { WalletConnectProvider } from "@/providers/wallet-connect-provider";
import RecoilContextProvider from "@/providers/recoil-provider";

import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const goodTiming = localFont({
  src: "./fonts/good-timing/good-timing-bd.otf",
  variable: "--font-good-timing",
});

export const metadata: Metadata = {
  title: "Conntree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${goodTiming.variable} antialiased bg-[#0A1117] text-white`}
      >
        <RecoilContextProvider>
          <WalletConnectProvider>
            <div className="flex flex-col h-screen overflow-hidden">
              {/* Header full width */}
              <Header />

              <div className="flex flex-1 overflow-hidden">
                {/* Sidebar on the left */}
                <Sidebar />

                {/* Page Content */}
                <main className="flex-1 overflow-y-auto p-6">{children}</main>
              </div>
            </div>
          </WalletConnectProvider>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
